dist: trusty
language: node_js
node_js:
  - "iojs"
  - "7"
before_install:
  - npm install -g git+https://github.com/ethereumjs/testrpc mocha solc node-hid
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g node-gyp node-hid rx
install: npm install
script:
- npm run test
